### ISSUE TITLE
Angular error

### ISSUE THREAD

**Issue by knkrth** [salvobertoncini/SpyWebApp#1]
Hi, What angular version you are using I use angular/cli -v 3.10.10 & I got the following error,

`kartx:~/workspace/spyapp $ sudo ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-10-06T09:50:10.829Z                                                        
Hash: 6fbefcd47722785c0d86
Time: 4913ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 1.06 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 323 bytes {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 56.5 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 338 kB [initial] [rendered]

ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (28,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdProgressBarModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (12,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdAutocompleteModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (14,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdButtonToggleModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (15,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdCardModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (16,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdCheckboxModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (17,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdChipsModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (18,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdDatepickerModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (19,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdDialogModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (20,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdExpansionModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (21,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdGridListModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (22,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdIconModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (23,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdInputModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (24,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdListModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (25,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdMenuModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (26,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdNativeDateModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (27,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdPaginatorModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (13,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdButtonModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (29,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdProgressSpinnerModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (30,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdRadioModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (31,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdRippleModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (32,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdSelectModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (33,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdSidenavModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (34,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdSliderModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (35,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdSlideToggleModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (36,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdSnackBarModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (37,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdSortModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (38,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdTableModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (39,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdTabsModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (40,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdToolbarModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (41,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdTooltipModule'.
ERROR in /home/ubuntu/workspace/spyapp/src/app/app.module.ts (42,3): Module '"/home/ubuntu/workspace/spyapp/node_modules/@angular/material/material"' has no exported member 'MdStepperModule'.
ERROR in Error: MdButtonModule is not an NgModule
    at _getNgModuleMetadata (/home/ubuntu/workspace/spyapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (/home/ubuntu/workspace/spyapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at /home/ubuntu/workspace/spyapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:129:27
    at Array.reduce (native)
    at _extractLazyRoutesFromStaticModule (/home/ubuntu/workspace/spyapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (/home/ubuntu/workspace/spyapp/node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (/home/ubuntu/workspace/spyapp/node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (/home/ubuntu/workspace/spyapp/node_modules/@ngtools/webpack/src/plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (/home/ubuntu/workspace/spyapp/node_modules/@ngtools/webpack/src/plugin.js:443:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

webpack: Failed to compile.`

**Comment by salvatorebertoncini** [comment]
Hi karthik!

I'm using Angular 4, specifically angular/cli 1.4.3, typescript 2.3.4.

I remember you that if you want to run correctly you must use SpyTorch
server, a python-django server which you can find here
https://github.com/salvobertoncini/ServerTorch, and MongoDB.

Salvo

2017-10-06 11:51 GMT+02:00 karthik <notifications@github.com>:

**Comment by knkrth** [comment]
Yes I also checked ServerTorch works perfectly. Let me try with angular/cli 1.4.3 & let you know.

**Comment by knkrth** [comment]
Still I got the same error.

**Comment by salvatorebertoncini** [comment]
try this:

```
cd SpyWebApp
ng serve
```

tell me if it work for you

**Comment by knkrth** [comment]
Only after cd SpyWebApp we can run ng serve.

**Comment by knkrth** [comment]
I did,
cd SpyWebApp
npm install 
ng serve

**Comment by salvatorebertoncini** [comment]
I was sure this would worked for you! Some times I do some stuff automatically, I'm sorry. 
Soon I would write a user-manual, I promise!

**Comment by knkrth** [comment]
Ok.
